name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --verbose

  build:
    name: Build
    needs: test
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          mkdir -p whambam-${{ matrix.target }}
          cp target/${{ matrix.target }}/release/whambam whambam-${{ matrix.target }}/
          tar -czf whambam-${{ github.ref_name }}-${{ matrix.target }}.tar.gz -C whambam-${{ matrix.target }} whambam

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whambam-${{ matrix.target }}
          path: whambam-${{ github.ref_name }}-${{ matrix.target }}.tar.gz

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/whambam-*.tar.gz

  update-homebrew:
    name: Update Homebrew Formula
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: cloudy-native/homebrew-whambam
          token: ${{ secrets.GITHUB_TOKEN }}
          path: homebrew-tap

      - name: Get release info and update formula
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}

          # Get SHA256 checksums from the release
          ARM_SHA=$(curl -sL "https://github.com/cloudy-native/whambam.dev/releases/download/v${VERSION}/whambam-v${VERSION}-aarch64-apple-darwin.tar.gz" | shasum -a 256 | cut -d' ' -f1)
          INTEL_SHA=$(curl -sL "https://github.com/cloudy-native/whambam.dev/releases/download/v${VERSION}/whambam-v${VERSION}-x86_64-apple-darwin.tar.gz" | shasum -a 256 | cut -d' ' -f1)

          # Update the formula
          cat > homebrew-tap/Formula/whambam.rb << EOF
          class Whambam < Formula
            desc "whambam: a simple CLI tool for web performance testing"
            homepage "https://github.com/cloudy-native/whambam.dev"
            license "MIT"
            head "https://github.com/cloudy-native/whambam.dev.git", branch: "main"
            
            on_macos do
              if Hardware::CPU.arm?
                url "https://github.com/cloudy-native/whambam.dev/releases/download/v${VERSION}/whambam-v${VERSION}-aarch64-apple-darwin.tar.gz"
                sha256 "${ARM_SHA}"
              else
                url "https://github.com/cloudy-native/whambam.dev/releases/download/v${VERSION}/whambam-v${VERSION}-x86_64-apple-darwin.tar.gz"
                sha256 "${INTEL_SHA}"
              end
            end
            
            def install
              bin.install "whambam"
            end
            
            test do
              system "#{bin}/whambam", "--version"
            end
          end
          EOF

      - name: Commit and push formula update
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/whambam.rb
          git commit -m "Update whambam to ${GITHUB_REF#refs/tags/v}"
          git push
